Update latex_cite_completions.py
Line 287 was failing when trying to do cite completions. The reason:
     TypeError: Can't convert 'dict' object to str implicitly